<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserImport extends Model
{
    use HasFactory;
    public $fields = [

      0 => "id",
      1 => "username",
      2 => "firstname",
      3 => "lastname",
      4 => "companyname",
      5 => "division",
      6 => "department",
      7 => "title",
      8 => "street",
      9 => "city",
      10 => "state",
      11 => "postalcode",
      12 => "country",
      13 => "latitude",
      14 => "longitude",
      15 => "geocodeaccuracy",
      16 => "email",
      17 => "senderemail",
      18 => "sendername",
      19 => "signature",
      20 => "stayintouchsubject",
      21 => "stayintouchsignature",
      22 => "stayintouchnote",
      23 => "phone",
      24 => "fax",
      25 => "mobilephone",
      26 => "alias",
      27 => "communitynickname",
      28 => "isactive",
      29 => "issystemcontrolled",
      30 => "timezonesidkey",
      31 => "userroleid",
      32 => "localesidkey",
      33 => "receivesinfoemails",
      34 => "receivesadmininfoemails",
      35 => "emailencodingkey",
      36 => "profileid",
      37 => "usertype",
      38 => "usersubtype",
      39 => "startday",
      40 => "endday",
      41 => "languagelocalekey",
      42 => "employeenumber",
      43 => "managerid",
      44 => "lastlogindate",
      45 => "lastpasswordchangedate",
      46 => "createddate",
      47 => "createdbyid",
      48 => "lastmodifieddate",
      49 => "lastmodifiedbyid",
      50 => "systemmodstamp",
      51 => "numberoffailedlogins",
      52 => "suaccessexpirationdate",
      53 => "suorgadminexpirationdate",
      54 => "offlinetrialexpirationdate",
      55 => "wirelesstrialexpirationdate",
      56 => "offlinepdatrialexpirationdate",
      57 => "contactid",
      58 => "accountid",
      59 => "callcenterid",
      60 => "extension",
      61 => "federationidentifier",
      62 => "aboutme",
      63 => "loginlimit",
      64 => "currentstatus",
      65 => "profilephotoid",
      66 => "digestfrequency",
      67 => "defaultgroupnotificationfrequency",
      68 => "workspaceid",
      69 => "sharingtype",
      70 => "chatteradoptionstage",
      71 => "chatteradoptionstagemodifieddate",
      72 => "bannerphotoid",
      73 => "isprofilephotoactive",
      74 => "individualid",
      75 => "globalidentity"]
      ;
}
